### ISSUE TITLE
Better way to select PCI devices?

### ISSUE THREAD

**Issue by lukego** [SnabbCo/snabbswitch#587] opened 2015-08-07 11:23 UTC
Currently we are expecting users to specify their PCI devices with long specific strings like `0000:01:00.0`. This is inconvenient in many situations. Let us capture the interesting use cases and come up with a better scheme to support them. I will invent an ad-hoc syntax as a starting point: pretend it is the command-line syntax of a program based on Snabb Switch.

You could write `-d 01:00.0` to refer to a specific device. (That is the same syntax as now but allowing with an abbreviated form.)

You could write `-d :intel10g` to refer to any available device that suits the `intel10g` app/driver. This would be fine for a test application that can use any available port.

You could write `-d $a.0:intel10g -d $a.1` to specify a pair of ports with a common prefix i.e. the first two ports (`.0` and `.1`) on the same PCI card. This would be handy when running the `intel_app` selftest that can use any two ports provided that they are cabled directly together.

Could also be that it would be worth creating a convention for naming and grouping ports. This could become complex in a containerized environment if there are many programs accessing the same devices via `/sys/` but without a common filesystem.

**Comment by eugeneia** [comment] 2016-01-06 13:59
Closing because its a duplicate of solved issue #657.

**Closed by eugeneia** 2016-01-06 13:59 UTC
Labels: enhancement, idea
